#!/bin/csh
#SBATCH --job-name "Cluster_FTIR"
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=1-00:00:00

setenv OMP_NUM_THREADS 1
setenv MKL_NUM_THREADS 1
echo $MKL_NUM_THREADS

setenv WD $SLURM_SUBMIT_WORKDIR

echo $TMPDIR
cd $TMPDIR

cp $WD/run $TMPDIR
cp $WD/inp* $TMPDIR
cp $WD/stochastic $TMPDIR

./run

~/program/NISE_2017/NISE3/translate inpTra
time ~/program/NISE_2017/NISE3/NISE3 input2D
~/program/NISE_2017/NISE3/2DFFT input2D

cp *.log $WD
cp *.dat $WD

