#!/bin/csh
#SBATCH --job-name "Cluster_FTIR"
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=8
#SBATCH --time=0-00:30:00

setenv OMP_NUM_THREADS 8
setenv MKL_NUM_THREADS 1
echo $MKL_NUM_THREADS

setenv WD $SLURM_SUBMIT_DIR

echo $TMPDIR
cd $TMPDIR

cp $WD/run.sh $TMPDIR
cp $WD/inp* $TMPDIR
cp $WD/stochastic $TMPDIR

./run.sh

~/NISE/NISE_2017/bin/translate inpTra
time ~/NISE/NISE_2017/bin/NISE input2D
~/NISE/NISE_2017/bin/2DFFT input2D

cp *.log $WD
cp *.dat $WD

