#!/bin/csh
#SBATCH --job-name NISE3
#SBATCH --nodes=1
#SBATCH --ntasks=1

module restore
setenv OMP_NUM_THREADS 1
setenv MKL_NUM_THREADS 1

setenv WD $SLURM_SUBMIT_DIR

#echo $TMPDIR
#cd $TMPDIR

cp $WD/run $TMPDIR
cp $WD/inp* $TMPDIR
cp $WD/stochastic $TMPDIR

./run

~/program/NISE_2017/NISE3.1/translate inpTra
time ~/program/NISE_2017/NISE3.1/NISE3.1 inputAnalyse

#cp *.log $WD
#cp *.dat $WD
